### ISSUE TITLE
Migrate tests to JUnit Jupiter

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4166]
This issue is to track the migration of the test suite from JUnit 4 to JUnit 5:

- [x] spring-batch-infrastructure: #4125
- [x] spring-batch-core: #4172 
- [x] spring-batch-test: #4174 
- [x] spring-batch-integration: #4124
- [x] spring-batch-samples: #4173

**Comment by fmbenhassine** [comment]
Refinements like those done for `spring-batch-infrastructure` in #4175 can be done later for other modules. Improving test suites is a non-ending task, so I'm closing this for now as it is already a huge improvement to Spring Batch's test suite.

A BIG thank you to @hpoettker for this absolutely amazing contribution! REALLY appreciated 👍
